# Generated by Django 5.0.3 on 2024-12-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
