# Generated by Django 5.0.3 on 2024-12-29 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(
                default=uuid.UUID("5818d4aa-f12f-4375-b07e-a72de6b557c3"),
                null=True,
                unique=True,
            ),
        ),
    ]
