# Generated by Django 5.0.3 on 2024-12-29 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(
                default=uuid.UUID("c9d2be21-8340-44f1-9702-0476031cd673"),
                null=True,
                unique=True,
            ),
        ),
    ]
