# Generated by Django 5.0.3 on 2024-12-29 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_quantity_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(
                default=uuid.UUID("c7a96977-3bfa-4beb-aa3f-7208495c35ff"),
                null=True,
                unique=True,
            ),
        ),
    ]
