# Generated by Django 5.0.3 on 2024-12-29 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(
                default=uuid.UUID("1cd4c919-9bb2-45a2-8368-cd8f971b2be1"),
                null=True,
                unique=True,
            ),
        ),
    ]
