# Generated by Django 5.0.3 on 2024-12-29 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_vendor_is_approved_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(
                default=uuid.UUID("50e4017a-9153-4100-9d9e-1e769ff3303a"),
                null=True,
                unique=True,
            ),
        ),
    ]
