# Generated by Django 5.0.3 on 2024-12-29 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(
                default=uuid.UUID("9a483f59-4835-4786-896a-dca881b4cc66"),
                null=True,
                unique=True,
            ),
        ),
    ]
