# Generated by Django 5.0.3 on 2024-12-29 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.UUIDField(
                default=uuid.UUID("239cec65-e14c-4c74-9557-9eaebbd89d67"),
                null=True,
                unique=True,
            ),
        ),
    ]
