import os

SOLAPI_API_KEY = os.getenv("SOLAPI_API_KEY")
SOLAPI_API_SECRET = os.getenv("SOLAPI_API_SECRET")
SOLAPI_PF_ID = os.getenv("SOLAPI_PF_ID")
SOLAPI_PHONE_NUMBER = os.getenv("SOLAPI_PHONE_NUMBER")
ORDER_CREATE_TEMPLATE_ID = os.getenv("ORDER_CREATE_TEMPLATE_ID")
IN_DELIVERY_TEMPLATE_ID = os.getenv("IN_DELIVERY_TEMPLATE_ID")
