import os

TOSS_CLIENT_KEY = os.getenv("TOSS_CLIENT_KEY")
TOSS_SECRET_KEY = os.getenv("TOSS_SECRET_KEY")
TOSS_API_SECRET_KEY = os.getenv("TOSS_API_SECRET_KEY")
TOSS_API_URL = os.getenv("TOSS_API_URL")
