# Generated by Django 5.0.3 on 2024-12-29 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product_amount",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("discount", models.FloatField(blank=True, default=0.0, null=True)),
                ("grand_total", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "delivery_charge",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="order.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_products",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=255, unique=True
                    ),
                ),
                (
                    "delivery_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_amount",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("discount", models.FloatField(blank=True, default=0.0, null=True)),
                ("grand_total", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "delivery_charge",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("shipping_address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAYMENT_COMPLETE", "Payment Complete"),
                            ("PRODUCT_IN_PRODUCTION", "Product in Production"),
                            ("IN_DELIVERY", "In Delivery"),
                            ("DELIVERY_COMPLETE", "Delivery Complete"),
                            ("PURCHASE_CONFIRMATION", "Purchase Confirmation"),
                            ("RETURN_REQUEST", "Return Request"),
                            ("RETURNED_IN_PROGRESS", "Returned in Progress"),
                            ("RETURN_COMPLETE", "Return Complete"),
                            ("CANCEL_REQUEST", "Cancel Request"),
                            ("CANCEL_IN_PROGRESS", "Cancel in Progress"),
                            ("CANCEL_COMPLETE", "Cancel Complete"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CASH_ON_DELIVERY", "Cash on delivery"),
                            ("ONLINE_PAYMENT", "Online payment"),
                            ("PARTIAL_PAYMENT", "Partial payment"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                (
                    "payment_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("payment_response", models.JSONField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_orders",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
