# Generated by Django 5.0.3 on 2024-12-29 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_vendor"),
        ("product", "0009_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_product_vendor",
                to="product.vendor",
            ),
        ),
    ]
